### ISSUE TITLE
Series Info Window Not Populating Correctly

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/MyAnime3#65]
![image](https://cloud.githubusercontent.com/assets/9443295/21466472/579b637a-c982-11e6-86ab-8d5766adaaff.png)

Skins: All 

The series info shows when viewing your series list but not when viewing the actual series. 

Additional information including logs can be found here, http://forum.team-mediaportal.com/threads/my-anime-3.107475/page-94#post-1204957.

**Comment by RickDB** [comment]
That's odd, so this is for series that are not in a group (single series)?

**Comment by ElementalCrisis** [comment]
Just tried a couple more series, both single and in groups and it seems to affect them all. 

```[2016-12-24 02:51:08,956] [Error  ] [MPMain   ] [ERROR] - Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MyAnimePlugin3.MainWindow.LoadLocalThumbnail(Int32 episodeID)
   at MyAnimePlugin3.MainWindow.Episode_OnItemSelected(GUIListItem item)
   at MyAnimePlugin3.MainWindow.OnMessage(GUIMessage message)
   at MediaPortal.GUI.Library.GUIWindowManager.SendMessage(GUIMessage message)
[2016-12-24 02:51:14,065] [Error  ] [MPMain   ] [ERROR] - Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MyAnimePlugin3.MainWindow.LoadLocalThumbnail(Int32 episodeID)
   at MyAnimePlugin3.MainWindow.Episode_OnItemSelected(GUIListItem item)
   at MyAnimePlugin3.MainWindow.OnMessage(GUIMessage message)
   at MediaPortal.GUI.Library.GUIWindowManager.SendMessage(GUIMessage message)
[2016-12-24 02:51:14,595] [Error  ] [MPMain   ] [ERROR] - Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MyAnimePlugin3.MainWindow.LoadLocalThumbnail(Int32 episodeID)
   at MyAnimePlugin3.MainWindow.Episode_OnItemSelected(GUIListItem item)
   at MyAnimePlugin3.MainWindow.OnMessage(GUIMessage message)
   at MediaPortal.GUI.Library.GUIWindowManager.SendMessage(GUIMessage message)
[2016-12-24 02:51:15,124] [Error  ] [MPMain   ] [ERROR] - Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MyAnimePlugin3.MainWindow.LoadLocalThumbnail(Int32 episodeID)
   at MyAnimePlugin3.MainWindow.Episode_OnItemSelected(GUIListItem item)
   at MyAnimePlugin3.MainWindow.OnMessage(GUIMessage message)
   at MediaPortal.GUI.Library.GUIWindowManager.SendMessage(GUIMessage message)
[2016-12-24 02:51:15,532] [Error  ] [MPMain   ] [ERROR] - Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MyAnimePlugin3.MainWindow.LoadLocalThumbnail(Int32 episodeID)
   at MyAnimePlugin3.MainWindow.Episode_OnItemSelected(GUIListItem item)
   at MyAnimePlugin3.MainWindow.OnMessage(GUIMessage message)
   at MediaPortal.GUI.Library.GUIWindowManager.SendMessage(GUIMessage message)
[2016-12-24 02:51:16,061] [Error  ] [MPMain   ] [ERROR] - Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MyAnimePlugin3.MainWindow.LoadLocalThumbnail(Int32 episodeID)
   at MyAnimePlugin3.MainWindow.Episode_OnItemSelected(GUIListItem item)
   at MyAnimePlugin3.MainWindow.OnMessage(GUIMessage message)
   at MediaPortal.GUI.Library.GUIWindowManager.SendMessage(GUIMessage message)```

**Comment by RickDB** [comment]
Ah the LoadLocalThumbnail function, probably something that is no longer returning from server so will debug it :)

**Comment by RickDB** [comment]
Fixed LoadLocalThumbnail function and commented out the optional fanart part of it as it caused a delay especially for large series.
